<tr>
    <td class="hdr">Cliente aggiunto</td>
    <td>{{cliente.data_creazione|date:"d/m/Y"}}</td>
</tr>
<tr>
    <td class="hdr">Cod. ID</td>
    <td>{{cliente.codice_id}}</td>
</tr>
<tr>
    <td class="hdr">Cod. Impianto</td>
    <td >{{cliente.codice_impianto}}</td>
</tr>
<tr>
    <td class="hdr">Nome</td>
    <td >{{cliente.nome}}</td>
</tr>
<tr>
    <td class="hdr">Cognome</td>
    <td >{{cliente.cognome}}</td>
</tr>
<tr>
    <td class="hdr">Cod. Fiscale</td>
    <td >{{cliente.codice_fiscale}}</td>
</tr>
<tr>
    <td class="hdr">Via</td>
    <td>{{cliente.via}}</td>
</tr>
<tr>
    <td class="hdr">Citta</td>
    <td>{{cliente.citta}}</td>
</tr>
<tr>
    <td class="hdr">Telefono</td>
    <td>{{cliente.numero_telefono}}</td>
</tr>
<tr>
    <td class="hdr">Cellulare</td>
    <td>{{cliente.numero_cellulare}}</td>
</tr>
<tr>
    <td class="hdr">Mail</td>
    <td>{{cliente.mail}}</td>
</tr>
<tr>
    <td class="hdr">Caldaia</td>
    <td>{{cliente.marca_caldaia}}</td>
</tr>
<tr>
    <td class="hdr">Modello</td>
    <td>{{cliente.modello_caldaia}}</td>
</tr>
<tr>
    <td class="hdr">Tipo</td>
    <td>{{cliente.tipo}}</td>
</tr>
<tr>
    <td class="hdr">Combustibile</td>
    <td>{{cliente.combustibile}}</td>
</tr>
<tr>
    <td class="hdr">Data Installazione</td>
    <td>{{cliente.data_installazione|date:"d/m/Y"}}</td>
</tr>
<tr>
    <td class="hdr">Data Contratto</td>
    <td>{{cliente.data_contratto|date:"d/m/Y"}}</td>
</tr>
