{% extends "base.html" %}

{% block center_block %}
<h1>Eventi del giorno</h1>
<h2>{% now "d F Y H:i" %}</h2>

<form action="{% url home %}" method="get">{% csrf_token %}
<table>
<tr></tr>
<tr><td></td>
{% for field in data_form %}
    <td>{{field.label}}</td>
    <td>{{field}}{{field.errors}}</td>
{% endfor %}
<td>
<input type="submit" value="Aggiorna"/>
</td></tr>
<tr></tr>
</table>
</form>

{% autoescape off %}
    {{ data }}
{% endautoescape %}

Per ora nessun evento.
{% endblock %}
